---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

``` {r setup}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

We are going to look at "The Instacart Online Grocery Shopping Dataset 2017", we are only interested in items ordered in produce, snack, and beverage department on weekends.

```{r data import and clean}
data("instacart")

instacart = instacart |> 
  select(add_to_cart_order, reordered, order_number, department, aisle, days_since_prior_order, product_name, order_dow) |>
  filter(department %in% c("produce", "snacks", "beverages")) |>
  filter(order_dow %in% c("0", "6"))
```

The plot shows the number of items ordered in each aisle in produce, beverages, and snacks department.
```{r}
instacart |> 
  group_by(department) |>
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n),
         text_label = "Department", department) |> 
  plot_ly(
    x = ~aisle, y = ~n, type = "bar", color = ~department, text = ~text_label, alpha = 0.5)
  
```




