---
output: 
  html_document:
    toc: true
    toc_float: true
---

<div style="text-align:center;">
# Yvonne Chen
530-407-8932 | sc5078@cumc.columbia.edu

Research interest: biostatistics, infectious disease and epidemiology

<div style="text-align:left;">
## Education

<b>Columbia University</b>

Master of Public Health in Biostatistics

GPA: 3.99/4.0

• Public Health Courses: Research Methods & Application, Determinants of Health, Public Health Interventions, Health Systems, Decision Analysis for Clinical and Public Health Practice, Personal leadership in public health

• Biostatistics Course: Applied Regression, analysis of categorical data, Statistical Computing with SAS, Data Science, Mathematical Statis, Analysis of Large-Scale D, STRATEGIC ISSUES IN HEALT

<b>University of California, Davis</b>

Bachelor of Science Major in Nutrition, Minor in Statistics

GPA: 3.614/4.0

• Nutrition Courses: Intro Nut & Metabolism, Nutritional Assessment, Clinical Nutrition, Nutrition Practicum, Community Nutrition, Food Chemistry Clinical Nutrition, Proseminar in Nutrition

• Life Courses: Gene & Gene Expression, Intro Microbiology (with Lab), Animal Biochemistry & Metabolism, Systemic Physiology Lab

• Statistics Courses: Calculus (I, II, III), Elementary Statistics, Regression Analysis, Analysis of Variance, Brief Math Statistics

## Research Experience

<b>Graduate Student, Columbia University Irving Medical Center</b>

Department of Dermatology

Director: David M. Owens

• Conducted spatial gene expression analysis for formalin-fixed paraffin-embedded (FFPE) data using Space Ranger pipeline.

• Analyzed Spatial Transcriptomics results, identifying human skin cell types using spatial clustering plots.

• Integrated data analysis and biological knowledge to identify crucial cells in Actinic Keratoses, potentially contributing to cutaneous squamous cell carcinoma.


<b>Graduate Student, Columbia University Irving Medical Center</b>

Department of Biostatistics

Director: Jinhua Hu

• Engaged in longitudinal analysis research, including algorithm understanding and dataset exploration.

• Applied statistical modeling to DIABIMMUNE Microbiome Project datasets, explored the impact of specific taxa on infant type 1 diabetes development.

• Investigated the impact of Phylogenetic tree information on model efficiency.


<b>Undergraduate Student, The University of Texas at San Antonio</b>

Health Science Center

Director: Qianjin Guo

• Read literatures, and compared concepts, workflows, and applications of two kinds of RNA-seq technology.

• Put the emphasis of the result interpretation for bulk mRNA-seq and single-cell RNA-seq, including the data visualization technique and statistical analysis.

## Practical Experience

<b>Allergic to Salad</b>

Food educator

• Designed and executed engaging cooking activities for children, fostering curiosity and understanding of food and nutrition.

<b>Shanghai Pudong Centers for Disease Control and Prevention</b>

Intern

• Executed comprehensive food sampling in convenience stores, contributing to data-driven food safety initiatives.

• Assisted in the coordination of National Nutrition Week, including event planning and nutrition-related content creation.

<b>Health and Civilization Monitoring in Jiaxing, Zhejiang Health Bureau</b>

Data Collector

• Spearheaded data collection efforts to analyze the impact of COVID-19 on safety practices in various public settings.

• Generated insightful reports outlining findings and recommendations for public health interventions.

<b>UC Davis Medical Center-Cardiac Rehabi</b>

Volunteer

• Aided post-cardiac procedure patients, monitoring vital signs and guiding exercises.

• Demonstrated stretching/resistance-training exercises.

## Skills
Computer skills: Proficient in R, python, SAS, Stata.

Languages: Native in Chinese, and proficient in English